@echo off
echo Checking environment configuration...
if not exist .env (
    echo [WARNING] .env file is missing! Copying .env.example to .env...
    copy .env.example .env
)

echo Starting Medixpro servers (building containers)...
docker compose up -d --build
echo Servers are starting...
timeout /t 10 /nobreak > nul
echo Opening website...
start http://localhost:3000
echo Done. Terminal will close in 2 seconds...
timeout /t 2 /nobreak > nul
