@echo off
echo Checking environment configuration...
if not exist .env (
    echo [WARNING] .env file is missing! Copying .env.example to .env...
    copy .env.example .env
)

echo Starting Medixpro servers (building containers)...
docker compose up -d --build
echo Servers are starting...
ping 127.0.0.1 -n 11 > nul
echo Opening website...
start http://localhost:3000
echo Done. Terminal will close in 2 seconds...
ping 127.0.0.1 -n 3 > nul
